steps:
  - name: "gcr.io/cloud-builders/git"
    args: ["clone", "https://github.com/YUPBL-SK/PBL_final.git"]

  # 다른 빌드 단계 추가 가능 (의존성 설치, 테스트 등)

  - name: "gcr.io/cloud-builders/gsutil"
    args: ["cp", "gs://pbl-model/1842_RF1000_142dd2.joblib", "server/"]

  - name: "gcr.io/cloud-builders/gsutil"
    args: ["cp", "gs://pbl-model/RPM297303_RF1000.joblib", "server/"]

  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/pbl-docker:$COMMIT_SHA", "."]

  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/pbl-docker:$COMMIT_SHA"]

  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - "compute"
      - "ssh"
      - "pbl-instance"
      - "--project=$PROJECT_ID"
      - "--zone=asia-northeast3-a"
      - "--command=docker run -d -p 5000:5000 gcr.io/$PROJECT_ID/pbl-docker:$COMMIT_SHA"
