steps:
  - name: "gcr.io/cloud-builders/git"
    args: ["clone", "https://github.com/YUPBL-SK/PBL_final.git"]

  # 다른 빌드 단계 추가 가능 (의존성 설치, 테스트 등)

  - name: "gcr.io/cloud-builders/gsutil"
    args: ["cp", "gs://pbl-model/1842_RF1000_142dd2.joblib", "server/"]

  - name: "gcr.io/cloud-builders/gsutil"
    args: ["cp", "gs://pbl-model/RPM297303_RF1000.joblib", "server/"]

  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/pbl-final:$COMMIT_SHA", "."]

  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/pbl-final:$COMMIT_SHA"]

  # Deploy to Cloud Run
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - "run"
      - "deploy"
      - "pbl-final"
      - "--image=gcr.io/$PROJECT_ID/pbl-final:$COMMIT_SHA"
      - "--region=asia-northeast3"
      - "--allow-unauthenticated"
      - "--memory=10Gi"
      - "--cpu=3"
